[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
    " let g:lightline = {'colorscheme': 'tender'}
    let g:lightline = {
    \  'colorscheme': 'wombat',
    \  'active': {
    \    'left': [
    \      ['mode', 'paste'],
    \      ['readonly', 'filename', 'modified', 'ale'],
    \    ]
    \  },
    \  'component_function': {
    \    'ale': 'ALEGetStatusLine'
    \  }
    \}
'''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
    colorscheme tender
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'


[[plugins]] repo = "Shougo/deoplete.nvim"
hook_add = '''
    source ~/.config/nvim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    nmap <silent> <F10> <Plug>(ale_next_wrap)
    nmap <silent> <F9> <Plug>(ale_previous_wrap)
    let g:ale_sh_shellcheck_options="-x"
    let g:ale_echo_msg_error_str = 'E'
    let g:ale_echo_msg_warning_str = 'W'
    let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
    let g:ale_statusline_format = ['E%d', 'W%d', 'OK']
'''

[[plugins]] #ファイラー
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'vim-scripts/gtags.vim'
hook_add = '''
	nmap <silent> <C-t> :GtagsCursor<CR>
	nmap <C-n> :cn<CR>
	nmap <C-p> :cp<CR>
'''

[[plugins]]
repo = 'ozelentok/denite-gtags'



[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'


[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'
